name=SuperOTA
version=1.1.9
author=João Augusto Carvalho Araújo
maintainer=João Augusto Carvalho Araújo
sentence=Subbiblioteca OTA da Baratinha para ESP32 com fallback STA/AP e portal de configuracao.
paragraph=Fornece OTA por WiFi com scan inteligente de redes station, mDNS, serial via Telnet, portal web e persistencia em NVS.
category=Communication
url=https://github.com/joaoaugustocz/SuperOTA
architectures=esp32
includes=SuperOTA.h
